### ISSUE TITLE
Review sample

### ISSUE THREAD

**Issue by AngeloSant0s** [AngeloSant0s/disabilities-brazil#3]
# Description

These are todos to verify if my sample is correct

# Todos

- [ ] Verify special schools, exclusive are the ones we will drop
- [ ] Verify classrooms information
- [ ] Verify the merge for SPAECE and census, why am I missing a lot of students
- [ ] Verify outcomes (new, drop, grade completion)
- [ ] Verify if I am doing this for Brazil
