### ISSUE TITLE
Meeting notes

### ISSUE THREAD

**Issue by AngeloSant0s** [AngeloSant0s/disabilities-brazil#4]
# April 10th

## Important miscellaneous

- Yona's idea in enrollment response of non-disabled. Do they leave schools with more disabled? Response to inclusion?

## Todos
 - [ ] Send my pdf with tables
 - [ ] Pre trends graphs:
    - [ ] Enrollment regular
    - [ ] Disabled enrollment
    - [ ] Disabled share
    - [ ] Average rank
    - [ ] Mental disability
 - [ ]  What are the controls I am using? create a list
 - [ ] Biasi's paper (Ask chinhui)
